### ISSUE TITLE
在 gitbook 2.5.0 中出现找不到 `core/state` 的错误

### ISSUE THREAD

**Issue by csbun** [gitbook-plugins/gitbook-plugin-search-pro#1]
将 `asssts/search-pro.js` 的[第一行](https://github.com/gitbook-plugins/gitbook-plugin-search-pro/blob/master/assets/search-pro.js#L1)改为：

``` javascript
require(['gitbook', 'lodash'], function(gitbook, _) {
    var events = gitbook.events;
    var sidebar = gitbook.sidebar;
    var state = gitbook.state;
    var storage = gitbook.storage;
```

**Comment by xunuo** [comment]
好的，我晚些时间回去看看，或者你能提交一个MR么？

BTW：机枪兵？你也喜欢玩星际？虚空之遗刚上线，貌似还不错。

**Comment by csbun** [comment]
提了一个 Pull Request #2 .

PS. 关于头像，年轻的时候玩星际1，现在都不玩了。

**Comment by csbun** [comment]
npm 上发布一个新版本麽？方便安装。

**Comment by xunuo** [comment]
喔，抱歉现在才看到，当时修改完就已经发了。
