### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by voxelbustersold** [gitbook-plugins/gitbook-plugin-search-pro#11]
Error on loading this plugin. Removing this plugin works fine without any issues. 

Please update to gitbook 3.0.3 and check once.

**Comment by ibigbug** [comment]
Same issue

![image](https://cloud.githubusercontent.com/assets/543405/15668184/862d308e-274c-11e6-9f21-4fe12804a76b.png)

**Comment by kxxoling** [comment]
Same issue occurred. Error here: https://github.com/gitbook-plugins/gitbook-plugin-search-pro/blob/master/main.js#L107

**Comment by Ruanxingzhi** [comment]
同。
报错：`TypeError: Arguments to path.join must be strings`

```
$ gitbook --version
CLI version: 2.3.0
GitBook version: 3.1.1
$ npm --version
1.4.21
$ node --version
v0.10.25
```

@xunuo

**Comment by flute** [comment]
@Ruanxingzhi 这么多评论我只服你，直接汉字往上码...666

**Comment by somax** [comment]
+1

**Comment by xsbreakaway** [comment]
same error

**Comment by andineck** [comment]
I got the same error with this environment:

$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.0.3

$ node -v
v6.9.1
$ npm -v
3.10.8

**Comment by tankilo** [comment]
Unlucky the same problem came across.....
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.finish (XXXXX/node_modules/gitbook-plugin-search-pro/main.js:107:35)
    at XXXXX/.gitbook/versions/3.2.2/lib/output/callHook.js:48:29
    at XXXXX/.gitbook/versions/3.2.2/lib/utils/promise.js:22:20
    at _fulfilled (XXXXX/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (XXXXX/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (XXXXX/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
    at XXXXX/.gitbook/versions/3.2.2/node_modules/q/q.js:857:14
    at runSingle (XXXXX/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
```
CentOS 7 64
```
$ node -v
v6.9.2
$ npm -v
3.10.9
$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
```
book.json
```
"plugins": [
        "-search",
        "search-pro@1.0.9"
    ],
    "pluginsConfig": {
        "search-pro": {
            "cutWordLib": "nodejieba",
            "defineWord": ["gitbook-use"]
         }
    }
}
```

**Comment by twheastasia** [comment]
same error.
According to this https://github.com/gitbook-plugins/gitbook-plugin-search-pro/blob/master/main.js#L107
And then I change the value of "config.output" into a certain directory name temporarily in the module. It works for me.

**Comment by xunuo** [comment]
抱歉，请问使用的gitbook是什么版本？2.x版本我已不准备再继续维护，准备更新为3.x :)
sorry, which version of gitbook do you use?

**Comment by xunuo** [comment]
抱歉，让你久等了，目前已支持到gitbook 3.x，请根据readme试用，新年快乐 :)
