### ISSUE TITLE
使用gitbook 安装时出错 Error: nodejieba@1.4.11 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by lxshui** [gitbook-plugins/gitbook-plugin-search-pro#15]
你好，不懂为啥我总是安装不成功。其他插件又可以正常安装。
错误信息为：
Error: nodejieba@1.4.11 install: node-gyp rebuild
Exit status 1
这是安装截图
![image](https://cloud.githubusercontent.com/assets/18578376/19637324/ff5d5516-9a00-11e6-87da-df326e71d340.png)

这是book.json截图

![image](https://cloud.githubusercontent.com/assets/18578376/19637386/656c02bc-9a01-11e6-98ad-f9e61cdcdda1.png)

我安装了提示信息中的node-gyp后再安装也提示这个错误信息，还是没成功。麻烦帮我看看是啥原因，谢谢了。

**Comment by zhangjikai** [comment]
今天我安装的时候也遇到这个问题了，我在Ubuntu下的解决办法：
- 删除 `nodejieba` 库

```
sudo npm uninstall -g nodejieba
```
- 删除主目录下的 `.node-gyp` 文件夹
- 重新安装 `nodejieba` 库

```
sudo npm install -g nodejieba@1.4.11
```

就是重新装 `nodejieba` 库之前，要把 `.node-gyp` 文件夹也删了，windows 下的我也不知道有没有这个文件夹，你可以找找。
另外就是我之前在windows 也尝试装过，一直都不成功，后来使用Ubuntu才装成功了。

**Comment by lxshui** [comment]
@zhangjikai 谢谢，不过我已经没有用这个插件了，以后在使用这个插件再捣鼓吧

**Comment by xunuo** [comment]
抱歉，请问使用的gitbook是什么版本？2.x版本我已不准备再继续维护，准备更新为3.x :)

**Comment by xunuo** [comment]
抱歉，让你久等了，目前已支持到gitbook 3.x，请根据readme试用，新年快乐 :)
