### ISSUE TITLE
有个安装使用的有关issue 

### ISSUE THREAD

**Issue by yanyiwu** [gitbook-plugins/gitbook-plugin-search-pro#4]
https://github.com/yanyiwu/nodejieba/issues/44#issuecomment-160504482

**Comment by sinalvee** [comment]
已经知道出错原因，是gitbook使用的npm版本太低了。
解决方法是`cd gitbook-plugin-search-pro & npm install`

**Comment by xunuo** [comment]
好的 那我这边close了
