### ISSUE TITLE
搜索脚本报错

### ISSUE THREAD

**Issue by applezqp** [gitbook-plugins/gitbook-plugin-search-pro#8]
gitbook 版本是 2.1.2， gitbook-plugin-search-pro 版本是 1.0.7，但是出现报错，请问是什么原因？

<img width="677" alt="00f14e1f-eff0-4829-86b4-c94599b9fae3" src="https://cloud.githubusercontent.com/assets/170783/13842088/549dd37c-ec67-11e5-84bd-a5c1ae757913.png">

**Comment by xunuo** [comment]
请问是什么报错，能提供报错信息么？谢谢。

**Comment by applezqp** [comment]
@xunuo 上面的截图不清晰？

**Comment by xunuo** [comment]
看到了 我处理一下

**Comment by lorrylockie** [comment]
遇到和 @applezqp 同样的问题 ，  filter代码报错

plugin version: 1.0.9 

gitbook version: 2.1.3

**Comment by dingjjdingjj** [comment]
![image](https://cloud.githubusercontent.com/assets/17865709/15599632/174c2fd6-2417-11e6-8dea-3f984d6055fa.png)

**Comment by tddwm1990** [comment]
碰到 @dingjjdingjj 相同问题，在gitbook升级到3.0.3后出现

**Comment by xunuo** [comment]
抱歉，让大家久等了，目前已支持到gitbook 3.x，请根据readme试用，新年快乐 :)
